Repository daccotta-org/daccotta, pull requests merged in 2024-11, with the labels that each got.

#285 Added Rating Input in Journal Movie Page
  client/src/components/ui/stars.tsx
  client/src/pages/Journal/JournalPage.tsx
  client/src/services/journalService.ts
  server/controllers/journalController.ts
  server/models/User.ts
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#295 WIP: Added edit popup for modifying the journal entry
  client/src/pages/Journal/JournalPage.tsx
  client/src/services/journalService.ts
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#308 updated readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext
