Repository daccotta-org/daccotta, pull requests merged in 2024-10, with the labels that each got.

#70 Bug fix/improve ux
  .gitignore
  client/src/pages/List/MovieSearch.tsx
  client/src/pages/Onboard/(components)/TopMovies.tsx
  client/src/pages/SearchMovie/SearchMovie.tsx
  client/tailwind.config.js
  package-lock.json
  package.json
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#89 Fixed #79 : Fixed "auto-label" GitHub workflow
  .github/workflows/auto-label.yml
Labels: hacktoberfest, gssoc-ext, level 2

#122 Added new route for including a new movie in existing list
  client/src/services/userService.ts
  server/routes/listRoutes.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#130 ADD CICD Github Workflow for (auto-label, check-merge-conflicts, post-pr-thankyou, restrict_issues)
  .github/workflows/auto-label.yml
  .github/workflows/check-merge-conflicts.yml
  .github/workflows/post-pr-thankyou.yml
  .github/workflows/restrict_issues.yml
  package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#144 Add toast to the friends group and watch list
  client/src/components/ui/DockBar.tsx
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: bug, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#145 fix friend page responsiveness and add toll tip
  client/src/components/custom/Navbar/TestNavbar.tsx
  client/src/pages/Friends/Friends.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#147 Add pending count
  client/src/pages/Friends/Friends.tsx
Labels: enhancement, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#151 Fix Debouce on all buttons
  client/src/components/ui/Loader.tsx
  client/src/pages/CreateList/CreateList.tsx
  client/src/pages/Friends/Friends.tsx
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: bug, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#154 ADD Remove fav for movie on Movie Detail Page
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#157 Add Search history feature
  client/src/pages/SearchMovie/SearchMovie.tsx
Labels: enhancement, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#155 fix jounel card click and mobile responsive design on pendin request
  client/src/pages/Friends/Friends.tsx
  client/src/pages/Journal/JournalPage.tsx
Labels: bug, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#179 Add margin to dock to fit safari browser
  client/src/components/ui/DockBar.tsx
Labels: bug, frontend, hacktoberfest, gssoc-ext, level 1

#180 Hide the view details button in mobile view
  client/src/components/custom/MovieCarousel/CarouselCard.tsx
Labels: bug, frontend, hacktoberfest, gssoc-ext, level 1

#193 Fix button on hover
  client/src/pages/Journal/JournalPage.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#181 Revamp movie detail page
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: enhancement, frontend, hacktoberfest, gssoc-ext, level 3

#201 add-watchlist-functionality
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#131 Add unique id in lists when creating a user during onboarding
  server/main.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#94 Remove nested <form> element
  client/src/pages/Onboard/(components)/UsernameAndPictures.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#212 Make all font to white color on create list pop-up
  client/src/index.css
  client/src/pages/CreateList/CreateList.tsx
Labels: bug, frontend, hacktoberfest, hacktoberfest-accepted, level 2

#214 Fix for movies with no release date
  client/src/pages/MoviePage/MovieDetailPage.tsx
  server/models/movie.ts
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#210 Fix ui changes
  client/src/components/ui/dialog_mui.tsx
  client/src/pages/Journal/JournalPage.tsx
  client/src/pages/SearchMovie/SearchMovie.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#219 Handeled navigation and toaster on click on settings
  client/src/components/ui/dialog_mui.tsx
Labels: bug, frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#233 Added Google Sign In & Google Sign Up methods
  client/public/google.svg
  client/src/pages/auth/SignInPage2.tsx
  client/src/pages/auth/SignUpPage2.tsx
  package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#224 Add Delete list functionality to the lists
  client/src/pages/List/UserList.tsx
  client/src/services/userService.ts
  server/package-lock.json
  server/routes/listRoutes.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#239 fixed movieDetailPage
  client/src/components/custom/MovieCarousel/CarouselCard.tsx
  client/src/components/custom/MovieCarousel/MovieCarousel.tsx
  client/src/pages/MoviePage/MovieDetailPage.tsx
  client/src/pages/auth/SignInPage2.tsx
  client/src/pages/auth/SignUpPage2.tsx
Labels: bug, documentation

#235 Added forget password with firebase
  client/src/pages/auth/SignInPage2.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#246 Add back button to list and list icon to navbar
  client/src/components/custom/Navbar/TestNavbar.tsx
  client/src/pages/List/MovieList.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#247 add validation to create list form
  client/src/pages/CreateList/CreateList.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#253 ADD TABLE OF CONTENT ON README FILE
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#249 Added Logout button on sidebar
  client/src/components/custom/Navbar/TestNavbar.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#241 Added entry in backend when sign up using Google
  client/src/pages/auth/SignInPage2.tsx
  client/src/pages/auth/SignUpPage2.tsx
  client/src/services/userService.ts
Labels: enhancement, hacktoberfest, gssoc-ext, level 3

#251 Disable selection of future dates
  client/src/components/ui/calendar.tsx
  client/src/pages/Journal/JournalPage.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#252 Add: Avatar Selection Modal and Profile Image Update Functionality
  client/src/pages/Onboard/(components)/UsernameAndPictures.tsx
  client/src/pages/Profile/AvatarSelectionModal.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/services/userService.ts
  server/controllers/userController.ts
  server/routes/userRoutes.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#265 Update README with New Badges and Improved Documentation [Fixed #260]
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#273 fix/build
  client/src/components/ui/dialog_mui.tsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext

#274 fixed list
  client/src/pages/List/UserList.tsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext

#267 Enhance and structure the Contributors Section
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#256 Update Contact Channel in Readme.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#279 Fix watchlist and favlist bug of adding new movie
  client/src/pages/MoviePage/MovieDetailPage.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#278 Implemented Sorting Functionality for Journal Entries by Month and Year
  client/src/pages/Journal/JournalPage.tsx
Labels: frontend, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2
